---
- block: 
  - name: fetch list
    command: "code --list-extensions"
    register: installed_list
    check_mode: no
    changed_when: no
  
  # - name: echo list
    # debug: 
      # msg: "{{ installed_list }}"

  - name: visual studio code install extension
    raw: "code --install-extension {{ item }}"
    when: "installed_list.stdout_lines | select('search', item) | list | length == 0"
    loop: "{{ code_extensions }}"

  tags:
    - vscode