- block:

  - name: homebrew cask packages install
    homebrew_cask: 
      name: '{{ homebrew_cask_packages }}'
      state: present
      install_options: 'appdir=/Applications'
      accept_external_apps: yes
      # greedy: yes
  tags:
    - homebrew_cask